name: snapp_cli
description: Dart CLI for Remote Flutter Development. Easily set up and remotely debug Flutter apps on Raspberry Pi and other devices. Snapp CLI automates configuration, supporting custom embedders like Flutter-pi.
version: 1.0.0
repository: https://github.com/Snapp-Embedded/snapp_cli
issue_tracker: https://github.com/Snapp-Embedded/snapp_cli/issues
topics:
  [
    raspberry-pi,
    embedded-systems,
    flutter,
    dart-cli,
    remote-debugging,
    flutter-pi,
    snapp-embedded,
  ]

environment:
  sdk: ">=3.2.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter_tools:
    sdk: flutter
  args: ^2.4.2
  path: ^1.8.3
  package_config: ^2.1.0
  file: ^7.0.0
  async: ^2.11.0
  collection: ^1.19.0
  dartssh2: ^2.8.2
  yaml: ^3.1.2
  mason_logger: ^0.2.15
  process: ^5.0.2
  pub_semver: ^2.1.4
  http: ^0.13.6
  recase: ^4.1.0
  interact_cli: ^2.4.0

dev_dependencies:
  lints: ^4.0.0

executables:
  snapp_cli: snapp

platforms:
  windows:
  linux:
  macos:

ignored_advisories:
  - GHSA-9v85-q87q-g4vg
  - GHSA-r285-q736-9v95